### ISSUE TITLE
Does UnmountVolumeAfterTimeMachine work on Sonoma?

### ISSUE THREAD

**Issue by hanshuebner** [BrianHenryIE/UnmountVolumeAfterTimeMachine#1]
Hey,

I've found this tool and while it seems to exactly do what I want, it does not seem to work on my MacBook Air running Sonoma.  I've installed it using mint, and when I start it I see this:

```
mecipt-1 1088_% ~/.mint/bin/UnmountVolumeAfterTimeMachine
No launchd agent set
launchd agent written
launchd agent startOnMount set
status: unloaded
```

When I manually start a Time Machine backup, it finishes, but the backup volume stays mounted.  Nothing is printed by UnmountVolumeAfterTimeMachine after the initial messages.  Am I missing something?

Thank you!
Hans

**Comment by BrianHenryIE** [comment]
Sorry for the slow reply: it works for me!

I hadn't actually backed up since upgrading so I did just now and it behaved as expected.

My first guess is you had the drive open in Finder, or a file open that's on that's on the drive, so it wasn't able to be ejected.

Please try it again. I presume since you installed it via Mint, it's still installed. Please:
* open Activity Monitor
* plug your drive in
* notice the drive show in Finder
* notice UnmountVolumeAfterTimeMachine in Activity Monitor
* notice Time Machine start (or start it)
* notice Time Machine complete (including cleanup)
* UnmountVolumeAfterTimeMachine should be absent from Activity Monitor
* your drive should be absent in Finder

Let me know how what happens for you.

**Comment by hanshuebner** [comment]
Hi,

thank you for getting back and confirming that the tool works on Sonoma.  I believe that my system is somehow behaving incorrectly in that the external hard drive does not show up in Finder, even though it is mounted and visible in the `/Volumes` directory.  My guess is that this misbehavior is also what causes UnmountVolumeAfterTimeMachine to not work.  I will try to figure out what's going on, resorting to recreating my user account from scratch if necessary (although that'd be a bit of a pain).

Kind regards,
Hans
